FROM --platform=linux/amd64 ubuntu:24.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get dist-upgrade -y && \
  apt-get install software-properties-common -y && \
  add-apt-repository ppa:deadsnakes/ppa -y && \
  apt-get update -y

RUN apt-get -y install \
  python3-pip \
  python3.13-dev \
  pkg-config \
  libgdal-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN ln -sfn /usr/bin/python3.13 /usr/bin/python3 && \
  ln -sfn /usr/bin/python3.13 /usr/bin/python && \
  ln -sfn /usr/bin/pip3 /usr/bin/pip

WORKDIR /aircraft

COPY ./requirements/dev.pip /aircraft/dev.pip
COPY ./requirements/base.pip /aircraft/base.pip
COPY ./requirements/constraints.pip /aircraft/constraints.pip

# Install python packages
RUN pip install -r dev.pip -c constraints.pip
