# Generated by Django 5.0.8 on 2025-02-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="team_type",
            field=models.CharField(
                choices=[
                    ("WING", "Kanat Takımı"),
                    ("FUSELAGE", "Gövde Takımı"),
                    ("TAIL", "Kuyruk Takımı"),
                    ("AVIONICS", "Aviyonik Takımı"),
                    ("ASSEMBLY", "Montaj Takımı"),
                ],
                default="WING",
                max_length=20,
                verbose_name="Takım Türü",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ad"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Soyad"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="şifre"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.team",
                verbose_name="Takım",
            ),
        ),
    ]
