# Generated by Django 5.0.8 on 2025-02-02 10:18

import aircraft.core.fields
import aircraft.core.helpers
import aircraft.core.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    aircraft.core.fields.AircraftPrimaryKeyField(
                        default=aircraft.core.helpers.generate_unique_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "part_type",
                    models.CharField(
                        choices=[
                            ("WING", "Kanat"),
                            ("FUSELAGE", "Gövde"),
                            ("TAIL", "Kuyruk"),
                            ("AVIONICS", "Aviyonik"),
                        ],
                        max_length=50,
                        verbose_name="Part Type",
                    ),
                ),
                (
                    "plane_type",
                    models.CharField(
                        choices=[
                            ("TB2", "TB2"),
                            ("TB3", "TB3"),
                            ("AKINCI", "AKINCI"),
                            ("KIZILELMA", "KIZILELMA"),
                        ],
                        default="TB2",
                        max_length=20,
                        verbose_name="Plane Type",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="accounts.team",
                        verbose_name="team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(aircraft.core.mixins.AdminUtilsMixin, models.Model),
        ),
    ]
