# Generated by Django 5.0.8 on 2025-02-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="team",
        ),
        migrations.AddField(
            model_name="part",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
