# Generated by Django 5.0.8 on 2025-02-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0002_remove_part_team_part_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="quantity",
        ),
    ]
