# Generated by Django 5.0.8 on 2025-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0003_remove_part_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted?"),
        ),
    ]
