# Generated by Django 5.0.8 on 2025-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0004_part_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="used_in_plane",
            field=models.BooleanField(default=False),
        ),
    ]
