# Generated by Django 5.0.8 on 2025-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0005_part_used_in_plane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="used_in_plane",
            field=models.BooleanField(default=False, verbose_name="Used in Plane?"),
        ),
    ]
