# Generated by Django 5.0.8 on 2025-02-02 13:15

import aircraft.core.fields
import aircraft.core.helpers
import aircraft.core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0006_alter_part_used_in_plane"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartUsage",
            fields=[
                (
                    "id",
                    aircraft.core.fields.AircraftPrimaryKeyField(
                        default=aircraft.core.helpers.generate_unique_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "quantity_used",
                    models.PositiveIntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_history",
                        to="plane_management.part",
                        verbose_name="Part",
                    ),
                ),
            ],
            bases=(aircraft.core.mixins.AdminUtilsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlaneAssembly",
            fields=[
                (
                    "id",
                    aircraft.core.fields.AircraftPrimaryKeyField(
                        default=aircraft.core.helpers.generate_unique_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "plane_type",
                    models.CharField(
                        choices=[
                            ("TB2", "TB2"),
                            ("TB3", "TB3"),
                            ("AKINCI", "AKINCI"),
                            ("KIZILELMA", "KIZILELMA"),
                        ],
                        max_length=20,
                        verbose_name="Plane type",
                    ),
                ),
                (
                    "parts_used",
                    models.ManyToManyField(
                        related_name="plane_assemblies",
                        through="plane_management.PartUsage",
                        to="plane_management.part",
                        verbose_name="Part used",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plane_assemblies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(aircraft.core.mixins.AdminUtilsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="partusage",
            name="plane_assembly",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_usage_history",
                to="plane_management.planeassembly",
                verbose_name="Plane Assembly",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partusage",
            unique_together={("part", "plane_assembly")},
        ),
    ]
