# Generated by Django 5.0.8 on 2025-02-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "plane_management",
            "0007_partusage_planeassembly_partusage_plane_assembly_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partusage",
            name="quantity_used",
        ),
    ]
