# Generated by Django 5.0.8 on 2025-02-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0008_remove_partusage_quantity_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="is_deleted",
        ),
    ]
