# Generated by Django 5.0.8 on 2025-02-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plane_management", "0009_remove_part_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="part_type",
            field=models.CharField(
                choices=[
                    ("WING", "Kanat"),
                    ("FUSELAGE", "Gövde"),
                    ("TAIL", "Kuyruk"),
                    ("AVIONICS", "Aviyonik"),
                ],
                max_length=50,
                verbose_name="Parça Türü",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="plane_type",
            field=models.CharField(
                choices=[
                    ("TB2", "TB2"),
                    ("TB3", "TB3"),
                    ("AKINCI", "AKINCI"),
                    ("KIZILELMA", "KIZILELMA"),
                ],
                default="TB2",
                max_length=20,
                verbose_name="Uçak Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="used_in_plane",
            field=models.BooleanField(default=False, verbose_name="Kullanıldı mı?"),
        ),
        migrations.AlterField(
            model_name="part",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="partusage",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_history",
                to="plane_management.part",
                verbose_name="Parça",
            ),
        ),
        migrations.AlterField(
            model_name="partusage",
            name="plane_assembly",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_usage_history",
                to="plane_management.planeassembly",
                verbose_name="Üretilen Uçak",
            ),
        ),
        migrations.AlterField(
            model_name="planeassembly",
            name="parts_used",
            field=models.ManyToManyField(
                related_name="plane_assemblies",
                through="plane_management.PartUsage",
                to="plane_management.part",
                verbose_name="Kullanılan parçalar",
            ),
        ),
        migrations.AlterField(
            model_name="planeassembly",
            name="plane_type",
            field=models.CharField(
                choices=[
                    ("TB2", "TB2"),
                    ("TB3", "TB3"),
                    ("AKINCI", "AKINCI"),
                    ("KIZILELMA", "KIZILELMA"),
                ],
                max_length=20,
                verbose_name="Uçak tipi",
            ),
        ),
        migrations.AlterField(
            model_name="planeassembly",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plane_assemblies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
    ]
